### ISSUE TITLE
Quecmanager Default Password

### ISSUE THREAD

**Issue by fallen20241** [iamromulan/RM551E-GL#14]
When I update the root password whether it be through the Openwrt GUI or through your script, it doesnt carry over to the Quecmanager Login Page.  

Do you know the default password to Quecmanager so I can see if there is an option to set the password through it?  

The hardware on this is a production release Fm190w flashed with the non-beta quectel 551 firmware.  Everything else seems to be working great from your repo.

**Comment by WTa-hash** [comment]
@fallen20241 - does your password contain special characters? I posted something related here: https://github.com/iamromulan/quectel-rgmii-toolkit/issues/89

**Comment by fallen20241** [comment]
Yes it did, I changed the password to one without special characters and this fixed the issue.  Thanks!
